### repositorio
Soria franz
https://github.com/FranzDS01/InteligenciaArtifical/blob/main/Laboratorios/lab09/Regresion_Multivariable.ipynb

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from datetime import datetime

In [47]:
def cargar_dataset(ruta):
    data=pd.read_csv(ruta)
    return data

In [48]:
def eliminar_columnas(columnas,data):
    data=data.drop(columnas, axis=1)
    return data

In [49]:
def convertir_categoricas_int(categoricas,data):
    for columna in categoricas:
        le = LabelEncoder()
        data[columna] = le.fit_transform(data[columna])
    return  data

In [50]:
def convertir_fechas_int(columna_fecha,data):
    for columna in columna_fecha:
         data[columna] = pd.to_numeric(data[columna].map(datetime.timestamp))
    return data

In [51]:
def llenar_null_int(columna_null,data):
    media_columna=data[columna_null].mean()
    data[columna_null]=data[columna_null].fillna(media_columna)
    return data

In [52]:
def graficar(x, y,labelX,labelY):
    # Grafica los puntos x e y en una figura nueva.
    fig = plt.figure()  # abre una nueva figura
    plt.plot(x, y, 'ro', ms=10, mec='k')
    plt.ylabel(labelY)
    plt.xlabel(labelX)

In [53]:
def featureNormalize(X):
    X_norm = X.copy()
    mu = np.zeros(X.shape[1])
    sigma = np.zeros(X.shape[1])

    mu = np.mean(X, axis=0)
    sigma = np.std(X, axis=0)
    X_norm = (X - mu) / sigma

    return X_norm, mu, sigma

In [54]:
def computeCostMulti(X, y, theta):
    # Inicializa algunos valores utiles
    m = y.shape[0]  # numero de ejemplos de entrenamiento
    J = 0
    h = np.dot(X, theta)
    J = (1/(2 * m)) * np.sum(np.square(h - y))

    return J

In [55]:
def gradientDescentMulti(X, y, theta, alpha, num_iters):
    # Inicializa algunos valores
    m = y.shape[0]  # numero de ejemplos de entrenamiento
    # realiza una copia de theta, el cual será acutalizada por el descenso por el gradiente
    theta = theta.copy()
    J_history = []
    for i in range(num_iters):
        theta = theta - (alpha / m) * (np.dot(X, theta) - y).dot(X)
        J_history.append(computeCostMulti(X, y, theta))

    return theta, J_history


In [56]:
def predicciones(X_array,mu,sigma,theta):
    X_array[1:] = (X_array[1:] - mu) / sigma
    price = np.dot(X_array, theta)   # Se debe cambiar esto
    print('Prediccion de la emision de CO2 , con la caracteristicas del coche de prueba: C02 {:.0f}'.format(price))

In [57]:

data=cargar_dataset('./Laboratorios/Datasets/emisionCarbonoCoches.csv')
categoricas=data.select_dtypes(include=['object']).columns
convertir_categoricas_int(categoricas,data)
data=data.to_numpy()
X=data[:,:4]
y=data[:,4]
m=y.shape[0]
X_norm, mu, sigma = featureNormalize(X)
X = np.concatenate([np.ones((m, 1)), X_norm], axis=1)
print(X)

[[ 1.          1.27418685 -0.70812829 -1.59336644 -2.10389253]
 [ 1.          0.48331225  1.19879986 -1.07190106 -0.55407235]
 [ 1.          0.87874955 -0.30666973 -1.59336644 -1.52166278]
 [ 1.         -1.09843694 -1.31031612 -1.85409913 -1.78973979]
 [ 1.          0.2855936  -0.10594045 -0.28970299 -0.63784641]
 [ 1.          1.4719055   1.39952913 -1.59336644 -1.52166278]
 [ 1.          0.87874955  0.09478883 -0.55043568 -0.76769621]
 [ 1.          0.08787496 -1.20995148 -0.28970299  0.3046118 ]
 [ 1.         -0.90071829  0.19515346 -0.28970299 -0.7551301 ]
 [ 1.         -1.49387424 -1.10958684 -0.0289703  -0.59595938]
 [ 1.         -0.30756234  0.39588274 -1.33263375 -1.30803892]
 [ 1.          1.0764682   1.29916449 -0.81116837 -1.26615189]
 [ 1.         -0.90071829  0.19515346 -1.59336644 -0.7551301 ]
 [ 1.         -0.70299964 -0.20630509 -0.0289703  -0.16871166]
 [ 1.         -0.50528099  0.49624738 -0.0289703   0.14125238]
 [ 1.          0.6810309  -0.80849293 -0.0289703   0.15

 #from sklearn.linear_model import LinearRegression
 enfoque baasado en minimos cuadrados Ordinary Least Squares, OLS

In [58]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import PolynomialFeatures

pf = PolynomialFeatures(degree=2)
regresion_lineal = LinearRegression()
print(X.shape)
X = pf.fit_transform(X)
print(X.shape)
regresion_lineal.fit(X,y)
y_pred = regresion_lineal.predict(X)
rmse=np.sqrt(mean_squared_error(y,y_pred))
r2=r2_score(y,y_pred)
print("error:",rmse)
print("R2:",r2)



(36, 5)
(36, 21)
error: 3.9467885613834985
R2: 0.7116786390414767


In [62]:
n_poly = (5 + 3)! / 3!5! = 56
print(n_poly)

SyntaxError: invalid syntax (2092806002.py, line 1)

In [59]:
X_array = np.array([[1,14, 1500, 105, 790]])
pf = PolynomialFeatures(degree=2)    # usaremos polinomios de grado 3
X_array = pf.fit_transform(X_array)

prediccion_test = regresion_lineal.predict(X_array)
print(prediccion_test)


[969845.65850606]


#SGDRegressor
Algortimo de regresion lineal
from sklearn.linear_model import SGDRegressor

In [60]:
from sklearn.linear_model import SGDRegressor
numero_iter=10000
alpha=0.01
modelo = SGDRegressor(max_iter=numero_iter, eta0=alpha)
modelo.fit(X, y)

SGDRegressor(max_iter=10000)

In [61]:
X_array = np.array([[1, 14, 10, 1000, 790]])
pf = PolynomialFeatures(degree=3)    # usaremos polinomios de grado 3
X_array = pf.fit_transform(X_array)
prediccion_test = modelo.predict(X_array)
print(prediccion_test)


ValueError: X has 56 features, but SGDRegressor is expecting 21 features as input.

In [ ]:
#alpha = 0.001  # alpha = 0.003
#num_iters = 12000
#theta = np.zeros(5)
#theta, J_history = gradientDescentMulti(X, y, theta, alpha, num_iters)
#print('Theta calculado a partir de la acuacion descenso de gradiente:{:s}'.format(str(theta)))
#x=np.arange(len(J_history))
#plt.plot(x, J_history, lw=2)
#plt.xlabel('Numero de iteraciones')

#plt.ylabel('Costo J')
#X_prueba=[1,1,1,1600,1390]
#predicciones(X_prueba,mu,sigma,theta)
#graficar(X[:,1:],y,'X','CO2')
#plt.plot(X[:,1:],np.dot(X, theta),lw=2)

# Ecuacion de la normal

In [ ]:
def normalEqn(X, y):
    theta = np.zeros(X.shape[1])
    theta = np.dot(np.dot(np.linalg.inv(np.dot(X.T, X)), X.T), y)
    return theta

In [ ]:
# Calcula los parametros con la ecuación de la normal
data=cargar_dataset('../Datasets/emisionCarbonoCoches.csv')
categoricas=data.select_dtypes(include=['object']).columns
data=convertir_categoricas_int(categoricas,data)
data.info()
data=data.to_numpy()
X=data[:,:4]
y=data[:,4]
X = np.concatenate([np.ones((m, 1)), X], axis=1)
theta = normalEqn(X, y)
# Muestra los resultados optenidos a partir de la aplicación de la ecuación de la normal
print('Theta calculado a partir de la ecuación de la normal: {:s}'.format(str(theta)))
# Estimar el precio para una casa de superficie de 1650 sq-ft y tres dormitorios
X_prueba=[1,1,1,1600,1390]#prediccion para este dato alrededor 108
price = np.dot(X_prueba, theta)
print('Prediccion de la emision de CO2, con la caracteristicas del coche de prueba :CO2{: .0f}'.format(price))


FileNotFoundError: [Errno 2] No such file or directory: '../Datasets/emisionCarbonoCoches.csv'